config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
    devise_scope :user do
    get "/login", :to => "users/sessions#new"
    get "/registration/information", :to => "users/registrations#new"
    post "/registration/information/create", :to => "users/registrations#create"
  end

resources :addresses, only: [:create]
resources :creditcards, only: [:new, :create]

resources :items
resources :mypage, only: [:index, :show, :edit]

root "items#index"

resources :items do
  member do 
    get "item_status"
  end
end

get '/toppage', to: 'test#index'
get '/signin', to: 'users#new'
get '/logout', to: 'mypage#logout'
get '/registration', to: 'registration#confirmation'
get "/registration/confirmation", to: "sms_confirmation#edit"
get "/registration/address", to: "addresses#new"


get '/profile', to: 'profile#index'
get '/mypage/card', to: 'mypage#index'
get '/mypage/card/create', to: 'mypage#create'
get '/registration', to: 'registrations#index'
get '/registration/new', to: 'sessions#new'
get "/registration/compleate", to: "compleate#edit"

get "/item", to: "item_details#index"
get "/item/item_status", to: "items#item_status"
get "/item/category_children", to: "items#category_children"

get "/privacypolicy", to: 'privacypolicy#index'

resources :items do
  get "/order/confirmation", to: "orders#show"
  post "/order/confirmation", to: "orders#create"
end
end

app/views/shared/_category_bar.html.haml
.category_list
  - @category_list.find_each do |parent_category| 
    -if parent_category[:ancestry] == nil
      %ul.parent_top
        %li.parent_list
          = parent_category[:name]
          %ul.child_top
            - parent_category.children.find_each do |child_category|
              %li.child_list
                = child_category[:name]
                %ul.gchild_top
                  - child_category.children.find_each do |gchild_category|
                    %li.gchild_list
                      = gchild_category[:name]

app/views/shared/_footer.html.haml
-# トップページのフッター（グローバルナビ部分）
-# 他ファイルと判別を付けるために頭文字kを付けている。後で消す必要あり。

.kfooter
  .kfooter__grobalnavi
    .kfooter__grobalnavi__1
      %p メルカリについて
      %ul
        %li 会社概要
        %li 採用情報
        %li プレスリリース
        %li 公式ブログ
        %li ガイドライン
    .kfooter__grobalnavi__2
      %p メルカリについて
      %ul
        %li 会社概要
        %li 採用情報
        %li プレスリリース
        %li 公式ブログ
        %li ガイドライン
    .kfooter__grobalnavi__3
      %p メルカリについて
      %ul
        %li 会社概要
        %li 採用情報
        %li プレスリリース
        %li 公式ブログ
        %li ガイドライン
    .kfooter__grobalnavi__4
      %p メルカリについて
      %ul
        %li 会社概要
        %li 採用情報
        %li プレスリリース
        %li 公式ブログ
        %li ガイドライン
    .kfooter__grobalnavi__5
      %p メルカリについて
      %ul
        %li 会社概要
        %li 採用情報
        %li プレスリリース
        %li 公式ブログ
        %li ガイドライン

app/views/shared/_header.html.haml
.kheader
  .kheader__menu
    =link_to "/" do
      = image_tag "mercarilogo.svg", class: "img"
    %input.form-contol.seach-input{name: "keyword", class: "search_icon",placeholder: "何かお探しですか？"}
    -# %i.fa.fa-search
  .navmenu
    %ul.navmenu__leftside-bar
      .k__category
        %li.fa.fa-list
        =link_to  'カテゴリーから探す'
        = render "shared/category_bar" 
        %li.fa.fa-tags
        =link_to  'ブランドから探す'
    %ul.navmenu__rightside-bar
      -# ----ログイン後のアイコン----
      - if user_signed_in?
        %li.fa.fa-heart
        =link_to  'いいね！一覧'
        %li.fa.fa-bell
        =link_to 'お知らせ'
        %li.fa.fa-check
        =link_to 'やることリスト'
        %li.fa.smile
        =link_to mypage_path(current_user), class: 'mypage' do
          マイページ
      - else
        =link_to signin_path, class: 'sign_up' do
          新規会員登録
        =link_to new_user_session_path, class: 'log_in' do
          ログイン

app/views/shared/_item_info.html.haml
.item-deteal
  .item-deteal__box
    %h1.item-deteal__box__title
      = @item.name
    .item-deteal__box__item
      .item-deteal__box__item__left
        .left-top
          = image_tag @item.item_images[0].image.url
        - @item.item_images.each do |item_image|
          .left-bottom
            %li.left-bottom__array
              = image_tag item_image.image.url

      %table.item-detail-table
        %tbody
          %tr
            %th 出品者
            %td.td-box
              =link_to mypage_path(current_user), class: "link-blue" do
                = @item.user.nickname
              .yyy.icon-top
                .item-user-ratings
                  = fa_icon 'smile-o', {class: "good-icons--pink"}
                  %span 11
                .item-user-ratings.icon-margin
                  = fa_icon 'meh-o', {class: "good-icons--orange"}
                  %span 3
                .item-user-ratings.icon-margin
                  = fa_icon 'frown-o', {class: "good-icons--blue"}
                  %span 0
          %tr
            %th カテゴリー
            %td.td-box
              -# - if @item.category.parent_id.name
                = link_to "#", class: "link-blue" do
                  %div
                    = @item.categories.parent_id.name #親
              = link_to "#" do
                .item-detail-table-sub-category{class: "link-blue"}
                  %i.icon-arrow-right
                  -# = "＞" + @item.categories.parent_id.name        #子
              = link_to "#" do
                .item-detail-table-sub-sub-category{class: "link-blue"}
                  %i.icon-arrow-right
                  -# = "＞" + @item.categories.name               #孫
          -# - if @item.brand
            %tr
              %th ブランド
              %td.td-box
                %a{href: "#", class: "link-blue"}
                  %div
                    = @item.brand
          - if @item.size
            %tr
              %th 商品のサイズ
              %td.td-box
                = @item.size
          %tr
            %th 商品の状態
            %td.td-box
              = @item.condition
          %tr
            %th 配送料の負担
            %td.td-box
              = @item.delivery_fee
          %tr
            %th 配送の方法
            %td.td-box
              = @item.delivery_way
          %tr
            %th 配送元地域
            %td.td-box
              %a{href: "#", class: "link-blue"}
                = @item.prefecture
          %tr
            %th 発送日の目安
            %td.td-box
              = @item.delivery_date

app/views/shared/_new_item_button.html.haml
-# 出品ボタン

.new_item_button
  = link_to new_item_path do
    .new_item_button__content
      %p 出品
      = fa_icon "camera"

app/views/shared/_sell_header.html.haml
%sell_header
  %h1.sell_header-link
    = link_to root_path do
      = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?1076135930"

app/views/shared/_side_bar.html.haml
.default-container
  %nav.mypage_nav
    %ul.mypage_nav__parent
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "マイページ", "#", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "お知らせ", "#", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "やることリスト", "#", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "いいね！一覧", "#", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "出品する", "#", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "出品した商品 - 出品中", "#", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "出品した商品 - 取引中", "#", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "出品した商品 - 売却済み", "#", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "購入した商品 - 取引中", "#", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "購入した商品 - 過去の取引", "#", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "ニュース一覧", "#", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "評価一覧", "#", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "ガイド", "#", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "お問い合わせ", "#", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
    %h3.mypage_nav__head メルペイ
    %ul.mypage_nav__parent
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "売上・振込申請", "#", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "ポイント", "#", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
    %h3.mypage_nav__head 設定
    %ul.mypage_nav__parent
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "プロフィール", "/profile", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "発送元・お届け先住所変更", "#", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "支払い方法", "#", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "メール/パスワード", "#", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "本人情報","/mypage/#{current_user.id}/edit", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "電話番号の確認", "#", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"
      %li.mypage_nav__parent__list
        .mypage_nav__parent__list__content
          = link_to "ログアウト", "/logout", class:"mypage_nav__parent__list__content__side_link"
          = fa_icon "chevron-right", class: "mypage_nav__parent__list__content__icon"