config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
    devise_scope :user do
    get "/login", :to => "users/sessions#new"
    get "/registration/information", :to => "users/registrations#new"
    post "/registration/information/create", :to => "users/registrations#create"
  end

resources :addresses, only: [:create]
resources :creditcards, only: [:new, :create]

resources :items
resources :mypage, only: [:index, :show, :edit]

root "items#index"

resources :items do
  member do 
    get "item_status"
  end
end

get '/toppage', to: 'test#index'
get '/signin', to: 'users#new'
get '/logout', to: 'mypage#logout'
get '/registration', to: 'registration#confirmation'
get "/registration/confirmation", to: "sms_confirmation#edit"
get "/registration/address", to: "addresses#new"


get '/profile', to: 'profile#index'
get '/mypage/card', to: 'mypage#index'
get '/mypage/card/create', to: 'mypage#create'
get '/registration', to: 'registrations#index'
get '/registration/new', to: 'sessions#new'
get "/registration/compleate", to: "compleate#edit"

get "/item", to: "item_details#index"
get "/item/item_status", to: "items#item_status"
get "/item/category_children", to: "items#category_children"

get "/privacypolicy", to: 'privacypolicy#index'

resources :items do
  get "/order/confirmation", to: "orders#show"
  post "/order/confirmation", to: "orders#create"
end
end

app/models/item.rb
class Item < ApplicationRecord
  
  has_many   :item_images, dependent: :delete_all
  #belongs_to :address, optional: true
  belongs_to :category, optional: true
  belongs_to :brand, optional: true
  belongs_to :prefecture, optional: true
  belongs_to :size, optional: true
  belongs_to :condition, optional: true
  belongs_to :delivery_fee, optional: true
  belongs_to :delivery_way, optional: true
  belongs_to :delivery_date, optional: true
  belongs_to :user, optional: true
  accepts_nested_attributes_for :item_images

  validates :name,
    presence: { message: "入力してください" },
    length: { maximum: 40, message: "40文字以下で入力してください" }
  validates :price,
    numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999, message: "販売価格は300以上9,999,999以内で入力してください" }
  validates :description,
    presence: { message: "入力してください" },
    length: { maximum: 1000, message: "1000文字以下で入力してください" }
  validates :condition_id,
    presence: { message: "選択して下さい" }
  validates :prefecture_id,
    presence: { message: "選択して下さい" }
  validates :delivery_fee_id,
    presence: { message: "選択して下さい" }
  validates :delivery_date_id,
    presence: { message: "選択して下さい" }
  validates :delivery_way_id,
    presence: { message: "選択して下さい" }
  validates :category_id,
    numericality: { greater_than: 0, message: "選択して下さい" }
    # validates :brand,
    #   length: { maximum: 40 }
  # validates :user_id,
  #   presence: true
  # validates :size_id,
  #   numericality: { greater_than: 0, message: "選択して下さい" }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index,:show]


  def index
    @category_list = Category.all
    @items = Item.all.includes(:item_images).limit(10).order("created_at DESC")
    # @item_images =ItemImage.all
    # @item_images =ItemImage.all
    # @ladies_items = Item.get_ladies.limit(5).includes(:item_images)
    # @mens_items = Item.get_mens.limit(5).includes(:item_images)
    # @Electric_items = Item.get_Electric.limit(5).includes(:item_images)
    # @hobby_items = Item.get_hobby.limit(5).includes(:item_images)
  end

  def show
  end

  def new
    @item = Item.new
    @parents = Category.where(ancestry: nil)  
    10.times{@item.item_images.build}
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      redirect_to '/items/new'
      #render :new, item_images: @item.item_images.build
    end
  end

  # def create
  #   @item = current_user.items.new(item_params)
  #   if @item.save
  #     redirect_to root_path
  #   else
  #     render :new, item_images: @item.item_images.build
  #   end
  # end

  # def show
  #   @item_images = @item.item_images(@item.id)
  # end

  def edit
    (10-@item.item_images.count).times{@item.item_images.build}
    @grand_parents = Category.where(ancestry: nil)
    @parents = Category.where(ancestry: @item.grand_parent_id)
    @categories = Category.where(ancestry: "#{@item.grand_parent_id}/#{@item.parent_id}")
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      redirect_to "/items/#{@item.id}/edit"
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    elsif
      render :index
    end
  end

  def item_status
    @item = Item.find(params[:id])
    @user = User.find(@item.user_id)
  end

  def category_children
    category_id = params[:categoryId]
    @categories = Category.where(ancestry: category_id.to_s)
    respond_to do |format|
      format.html {redirect_to new_item_path }
      format.json
    end
  end
  # def update
  # end

  # def destroy
  # end

  # def category_index
  # end

  # def brand_index
  # end

  # def first_category
  # end

  # def second_category
  # end

  # def third_category
  # end

  # def search
  # end

  private
  
  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :price, :description, :category_id, :prefecture_id, :condition_id, :delivery_fee_id, :delivery_way_id, :delivery_date_id, :parent_id, :grand_parent_id, item_images_attributes:[:id,:image]).merge(user_id: current_user.id, order_status: 1)
  end
  
end

# :price, :description, :brand_id, :size_id, :condition_id, 
#       :category_id, :delivery_fee_id, :prefecture_id, :delivery_date_id,  
#       :delivery_way_id, 

app/helpers/items_helper.rb
module ItemsHelper
  def converting_price(price)
    “¥#{price.to_s(:delimited, delimiter: ‘,’)}”
  end
  def commission_jpy(commission)
      “¥#{commission.floor.to_s(:delimited, delimiter: ‘,’)}”
  end
  def profit_jpy(profit)
      “¥#{profit.ceil.to_s(:delimited, delimiter: ‘,’)}”
  end
end

app/views/items/_item-box.html.haml
.item-box
  .item-box__image
    - @items.each do |item|
      = item.name
  .item-box__price
    = converting_price(item.price)
  .item-box__title
    ＝item.name

  -# .sold-out-box
  -#   .sold-out-text SOLD


%li.item-box
  =link_to item_path(item.id) do
    = image_tag item.item_images[0].image
    - if item.order_status_id == 2

  .item-box-text
    .text-box
      %h4
        = item.name
    .price
      = converting_price(item.price)
    .price-tax
      (税込)

app/views/items/edit.html.haml
.sell-page-container
  = form_for @item do |f|
    .sell-page-container__header
      %h1 商品の情報を入力
    .item_image.border-bottom
      .inner-box
        .title
          %h3 出品画像
          %h4 必須
        .sub-title
          %h6 最大10枚までアップロードできます
        .file-field-box
          = f.fields_for :item_images do |fi|
            .file-content
              .setimage
                - if fi.object.image?
                  = image_tag fi.object.image.url, class: "preview"
                - else
                  %button{class:"setimage__onclick", type:"button"}
              = fi.file_field :image, class: "file-upload"   
    .item_name.border-bottom
      .inner-box
        .title
          %h3 商品名
          %h4 必須
        = f.text_field :name, class:"item-box", placeholder: "商品名（必須40文字まで)"
        .title-item_detail
          %h3 商品の説明
          %h4 必須
        = f.text_area :description, class:"item-box", placeholder: "商品の説明（必須1,000字まで)"
    .item_detail.border-bottom
      .inner-box.flex
        .left
          %h5 商品の詳細
        .right
          .right-top-title.flex-start
            %h3 カテゴリー
            %h4 必須
          = f.select :grand_parent_id, @grand_parents.all.map{|p|[p.name,p.id]}, {prompt: "---"}, class:"item_select-box", id: "item_category_id"
          = f.select :parent_id, @parents.all.map{|p|[p.name,p.id]}, {prompt: "---"}, class:"item_select-box", id: "item-edit-select-box2"
          = f.select :category_id, @categories.all.map{|p|[p.name,p.id]}, {prompt: "---"}, class:"item_select-box", id: "item-edit-select-box3"
          .right-title.flex-start
            %h3 商品の状態
            %h4 必須
          = f.select :condition_id, Condition.all.collect{|p|[p.condition,p.id]}, {prompt: "---"}, class:"item_select-box"
    .item_delivery.border-bottom
      .inner-box.flex
        .left
          %h5 配送について 
          %span.fa.fa-question-circle
        .right
          .right-top-title.flex-start
            %h3 配送料の負担
            %h4 必須
          = f.select :delivery_fee_id, DeliveryFee.all.collect{|p|[p.fee,p.id]}, {prompt: "---"}, class:"item_select-box"
          .right-title.flex-start
            %h3 配送の方法
            %h4 必須
          = f.select :delivery_way_id, DeliveryWay.all.collect{|p|[p.way,p.id]}, {prompt: "---"}, class:"item_select-box"
          .right-title.flex-start
            %h3 発送元の地域
            %h4 必須
          = f.select :prefecture_id, Prefecture.all.collect{|p|[p.name,p.id]}, {prompt: "---"}, class:"item_select-box"
          .right-title.flex-start
            %h3 発送までの日数
            %h4 必須
          = f.select :delivery_date_id, DeliveryDate.all.collect{|p|[p.date,p.id]}, {prompt: "---"}, class:"item_select-box"
    .item_price.border-bottom
      .inner-box.flex
        .left
          %h5 販売価格(300〜9,999,999)
          %span.fa.fa-question-circle
        .right
          .right-upper
            .right-upper__left.flex-start
              %h3 価格
              %h4.center-null-false 必須
            .right-upper__right.flex
              %p ￥
              = f.text_field :price ,class: 'item-price_field',placeholder: "例)300", id: 'item-edit-price'
          .right-center.flex
            .right-center__left
              %h5 販売手数料 (10%)
            .right-center__right
              %h5#item-edit-fee -
          .right-lower.flex
            .right-lower__left
              %h3 販売利益 
            .right-lower__right
              %h1#item-edit-profit -
    .sell-button
      .inner-box
        .inner-box__upper
          %p 禁止されている出品、行為を必ずご確認ください。
          %p またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
          %p また、出品をもちまして加盟店規約に同意したことになります
        .inner-box__center
          = f.submit "変更する", class: "sell_button"
        .inner-box__lower
          = link_to "キャンセル", root_path, class: "sell-return"
          

app/views/items/index.html.haml
.wrapper
  .kheader
    .kheader__menu
      = link_to "/" do
        = image_tag "mercarilogo.svg", class: "img"
      %input.form-contol.seach-input{name: "keyword", class: "search_icon",placeholder: "何かお探しですか？"}
      -# %i.fa.fa-search
    .navmenu
      %ul.navmenu__leftside-bar
        .k__category
          %li.fa.fa-list
          =link_to  'カテゴリーから探す'
          = render "shared/category_bar" 
        %li.fa.fa-tags
        =link_to  'ブランドから探す'
      %ul.navmenu__rightside-bar
        -# ----ログイン後のアイコン----
        - if user_signed_in?
          %li.fa.fa-heart
          =link_to  'いいね！一覧'
          %li.fa.fa-bell
          =link_to 'お知らせ'
          %li.fa.fa-check
          =link_to 'やることリスト'
          %li.fa.smile
          %li.fa.fa-user
          =link_to mypage_path(current_user), class: 'mypage' do
            マイページ
        - else
          =link_to signin_path, class: 'sign_up' do
            新規会員登録
          =link_to new_user_session_path, class: 'log_in' do
            ログイン

  .slideshow
    = image_tag "topmain.jpg", class: "slideshow2", alt: ""
    = image_tag "https://www.mercari.com/jp/assets/img/featured/camp/ogp.jpg", class: "slideshow2", alt: ""
    = image_tag "https://activeblog.jp/wp-content/uploads/2018/12/695EA9E6-21CA-4ED7-B86F-AF70266FEFB0.png", class: "slideshow2", alt: ""

  .populerlists
    .populerlists__title
      人気のカテゴリー
    %ul.populerlists__categolies
      %li.list
        =link_to 'レディース',class: "lists"
      %li.list
        =link_to 'メンズ',class: "lists"
      %li.list
        =link_to '家電・スマホ・カメラ',class: "lists"
      %li.list
        =link_to 'おもちゃ・ホビー・グッズ',class: "lists"

  .itemstitle
    .itemstitle__title
      新着アイテム
    .itemstitle__nextpage
      もっと見る
      %i.fa.fa-angle-right

  .item-box
    .item-box__contents
      - @items.each do |item|
        .item-box__contents__box
          .item-box__contents__box__image
            =link_to "/items/#{item.id}" do
              = image_tag item.item_images[0].image.url, height: "188px" , width: "188px"
            .item-box__contents__box__image__price
              ¥
              = item.price.to_s(:delimited)
            .item-box__contents__box__image__name
              = item.name
            - if item.order_status == 0
              .item-box__contents__box__image__soldout
                .item-box__contents__box__image__text
                  sold

  .advertisement
    .advertisement__list
      .advertisement__list__left
        %h2 スマホでかんたんフリマアプリ
        %p 今すぐ無料ダウンロード！
        = image_tag "mercari_icon.png", class: "mercari_icon"
        = image_tag "app-storeicon.svg", class: "app-storeicon"
        = image_tag "google-storeicon.svg", class: "google-storeicon"

      .advertisement__list__right
        = image_tag "smartphonepic.png",class: "smartphonepic"

  = render "shared/footer"
  = render "shared/new_item_button"

app/views/items/item_status.html.haml
= render "shared/header"
.item_status-content
  .item_status-content__inner
    .item-name
      = @item.name
    .item-main
      .item-main__left
        .item_photo
          = image_tag @item.item_images[0].image.url
          .item_photo__bottom
            .item_photo__bottom__array
              - @item.item_images.each do |item_image|
                = image_tag item_image.image.url
          
      .item-main__right
        .item-main__right__container
          .item-main__right__container--left
            .list-box
              %h3 出品者
            .list-box__category
              %h3 カテゴリー
            .list-box
              %h3 ブランド
            .list-box
              %h3 商品の状態
            .list-box
              %h3 配送料の負担
            .list-box
              %h3 配送の方法
            .list-box
              %h3 配送元地域
            .list-box
              %h3 発送日の目安
          .item-main__right__container--right
            .list-box
              %h4.user-name
                = @item.user.nickname
            .list-box__category
              %h4
                = @item.category.parent.parent.name
                %br
                = fa_icon 'angle-right'
                = @item.category.parent.name
                %br
                = fa_icon 'angle-right'
                = @item.category.name
            .list-box
              %h3 
            .list-box
              %h3 
                = @item.condition.condition
            .list-box
              %h3 
                = @item.delivery_fee.fee
            .list-box
              %h3 
                = @item.delivery_way.way
            .list-box
              %h4  
                = @item.prefecture.name
            .list-box
              %h3 
                = @item.delivery_date.date
    .item-price-box
      %p 
        ¥
        = @item.price.to_s(:delimited)
      %h2（税込）
    .item-desctiption-inner
      %h3 
        = @item.description
  .item_status-content__inner--second
    .item_status-content__button-red
      = link_to "商品の編集", edit_item_path(@item.id)
    .texr-center
      %h3 or
    .item_status-content__button-gray
      %h3 出品を一時停止する
    .item_status-content__button-gray
      = link_to "商品の削除", item_path(@item.id), method: :delete, data:{ confirm: "削除すると2度と復活できません。削除する代わりに停止することもできます。本当に削除しますか？"}

  .item_status-content__inner--third
    .item_status-content__attention
      相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
    .item_status-content__comment
      %textarea.comment_field     
    .item_status-content__submit
      %h3 コメントする
      
= render "shared/footer"

app/views/items/new.html.haml
= render "shared/sell_header"

.sell-page-container
  = form_for @item do |f|
    .sell-page-container__header
      %h1 商品の情報を入力
    .item_image.border-bottom
      .inner-box
        .title
          %h3 出品画像
          %h4 必須
        .sub-title
          %h6 最大10枚までアップロードできます
        .file-field-box
          = f.fields_for :item_images do |fi|
            .file-content
              .setimage
                %button{class:"setimage__onclick", type:"button"}
              = fi.file_field :image, class: "file-upload"
    .item_name.border-bottom
      .inner-box
        .title
          %h3 商品名
          %h4 必須
        = f.text_field :name, class:"item-box", placeholder: "商品名（必須40文字まで)"
        %p 入力してください
        .title-item_detail
          %h3 商品の説明
          %h4 必須
        = f.text_area :description, class:"item-box", placeholder: "商品の説明（必須1,000字まで)"
    .item_detail.border-bottom
      .inner-box.flex
        .left
          %h5 商品の詳細
        .right
          .right-top-title.flex-start
            %h3 カテゴリー
            %h4 必須
          = f.select :grand_parent_id, @parents.all.map{|p|[p.name,p.id]}, {prompt: "---"}, class:"item_select-box", id:"item_select-box1"
          .right-title.flex-start
            %h3 商品の状態
            %h4 必須
          = f.select :condition_id, Condition.all.collect{|p|[p.condition,p.id]}, {prompt: "---"}, class:"item_select-box"
    .item_delivery.border-bottom
      .inner-box.flex
        .left
          %h5 配送について 
          %span.fa.fa-question-circle
        .right
          .right-top-title.flex-start
            %h3 配送料の負担
            %h4 必須
          = f.select :delivery_fee_id, DeliveryFee.all.collect{|p|[p.fee,p.id]}, {prompt: "---"}, class:"item_select-box"
          .right-title.flex-start
            %h3 配送の方法
            %h4 必須
          = f.select :delivery_way_id, DeliveryWay.all.collect{|p|[p.way,p.id]}, {prompt: "---"}, class:"item_select-box"
          .right-title.flex-start
            %h3 発送元の地域
            %h4 必須
          = f.select :prefecture_id, Prefecture.all.collect{|p|[p.name,p.id]}, {prompt: "---"}, class:"item_select-box"
          .right-title.flex-start
            %h3 発送までの日数
            %h4 必須
          = f.select :delivery_date_id, DeliveryDate.all.collect{|p|[p.date,p.id]}, {prompt: "---"}, class:"item_select-box"
    .item_price.border-bottom
      .inner-box.flex
        .left
          %h5 販売価格(300〜9,999,999)
          %span.fa.fa-question-circle
        .right
          .right-upper
            .right-upper__left.flex-start
              %h3 価格
              %h4.center-null-false 必須
            .right-upper__right.flex
              %p ￥
              = f.text_field :price ,class: 'item-price_field',placeholder: "例)300"
          .right-center.flex
            .right-center__left
              %h5 販売手数料 (10%)
            .right-center__right
              %h5#item-new-fee -
          .right-lower.flex
            .right-lower__left
              %h3 販売利益 
            .right-lower__right
              %h1#item-new-profit -
    .sell-button
      .inner-box
        .inner-box__upper
          %p 禁止されている出品、行為を必ずご確認ください。
          %p またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
          %p また、出品をもちまして加盟店規約に同意したことになります
        .inner-box__center
          = f.submit "出品する", class: "sell_button"
        .inner-box__lower
          = link_to "もどる", root_path, class: "sell-return"
          
  .g_footer
    %ul.links
      %li
        =link_to "/", class: 'links__link-bottom' do
          プライバシーポリシー
      %li
        =link_to "/", class: 'links__link-bottom' do
          メルカリ利用規約
      %li
        =link_to "/", class: 'links__link-bottom' do
          特定商取引に関する表記
    =link_to "/" do
      = image_tag 'mercarilogo-gray.svg'
          

app/views/items/show.html.haml
.wrapper
  = render 'shared/header'

  .item-deteal
    .item-deteal__s-box
      %h1.item-deteal__s-box__title
        = @item.name
      .item-deteal__s-box__item
        .item-deteal__s-box__item__left
          .left-top
            = image_tag @item.item_images[0].image.url
            - if @item.order_status == 0
              .soldout
                .text  sold
          - @item.item_images.each do |item_image|
            .left-bottom
              %li.left-bottom__array
                = image_tag item_image.image.url

        %table.item-detail-table
          %tbody
            %tr
              %th 出品者
              %td.td-box
                - if current_user && @item.user_id == current_user.id
                  = link_to mypage_path(current_user), class: "link-blue" do
                    = @item.user.nickname
                - else
                  .link-blue
                    = @item.user.nickname
                .yyy.icon-top
                  .item-user-ratings
                    = fa_icon 'smile-o', {class: "good-icons--pink"}
                    %span 11
                  .item-user-ratings.icon-margin
                    = fa_icon 'meh-o', {class: "good-icons--orange"}
                    %span 3
                  .item-user-ratings.icon-margin
                    = fa_icon 'frown-o', {class: "good-icons--blue"}
                    %span 0
            %tr
              %th カテゴリー
              %td.td-box
                %h4
                  = @item.category.parent.parent.name
                  %br
                  = "> #{@item.category.parent.name}"
                  %br
                  = "> #{@item.category.name}"
              %tr
                %th ブランド
                %td.td-box
                  %a{href: "#", class: "link-blue"}
                    %div
                      = @item.brand
            - if @item.size
              %tr
                %th 商品のサイズ
                %td.td-box
                  = @item.size
            %tr
              %th 商品の状態
              %td.td-box
                = @item.condition.condition
            %tr
              %th 配送料の負担
              %td.td-box
                = @item.delivery_fee.fee
            %tr
              %th 配送の方法
              %td.td-box
                = @item.delivery_way.way
            %tr
              %th 配送元地域
              %td.td-box
                %a{href: "#", class: "link-blue"}
                  = @item.prefecture.name
            %tr
              %th 発送日の目安
              %td.td-box
                = @item.delivery_date.date

      - if current_user && @item.user_id == current_user.id
        .item-deteal__s-box__price
          %span.oooo
            ¥
            = @item.price.to_s(:delimited)
          %span.rrrr
            （税込）
          %span.wwww
            = @item.delivery_fee.fee
          %button.edit
            = link_to "商品の編集", edit_item_path(@item.id)
          .center
            %h3 or
          %button.stop
            出品を一時停止する
          %button.destroy
            = link_to "商品の削除", item_path(@item.id), method: :delete, data:{ confirm: "削除すると2度と復活できません。削除する代わりに停止することもできます。本当に削除しますか？"}
        .item-deteal__s-box__description
          %p.item-deteal__s-box__description__text
            = @item.description
      - else
        .item-deteal__s-box__price
          %span.oooo
            ¥
            = @item.price.to_s(:delimited)
          %span.rrrr
            （税込）
          %span.wwww
            = @item.delivery_fee.fee
          - unless @item.order_status == 0
            %button.sale
              - if current_user
                = link_to "/items/#{@item.id}/order/confirmation/" do
                  購入画面に進む
              - else 
                = link_to "/users/sign_in" do
                  購入画面に進む
          .item-deteal__s-box__description
            %p.item-deteal__s-box__description__text
              = @item.description

      .item-deteal__s-box__description__button
        .item-deteal__s-box__description__button__left
          %button.item-button.item-button-like
            %i.icon-like-border
            = fa_icon 'heart', {class: "icon-good"}
            %span いいね!
            %span.fade-in-bottom 3

        .item-deteal__s-box__description__button__report
          =link_to "http://www.kokusen.go.jp/t_box/t_box.html" do
            = fa_icon 'flag', {class: "icon-bad"}
            %span 不適切な商品の報告
        .item-deteal__s-box__description__button__right
          = link_to 'https://www.mercari.com/jp/safe/description/' do
            %i.icon-lock
            = fa_icon 'lock', {class: ".icon-lock"}
            %span あんしん・あんぜんへの取り組み

    .message-container
      .message-contents
        .message-container__contents__form
          %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
          %textarea.textarea-default
          %button.btn-default
            コメントする


  .advertisement
    .advertisement__list
      .advertisement__list__left
        %h2 スマホでかんたんフリマアプリ
        %p 今すぐ無料ダウンロード！
        = image_tag "mercari_icon.png", class: "mercari_icon"
        = image_tag "app-storeicon.svg", class: "app-storeicon"
        = image_tag "google-storeicon.svg", class: "google-storeicon"

      .advertisement__list__right
        = image_tag "smartphonepic.png",class: "smartphonepic"

  = render 'shared/footer'